const jokes = [
    "Why don't skeletons fight each other? They don't have the guts!",
    "I'm on a whiskey diet. I've lost three days already.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why do cows wear bells? Because their horns don’t work!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why don’t some couples go to the gym? Because some relationships don’t work out!",
    "Did you hear about the mathematician who’s afraid of negative numbers? He'll stop at nothing to avoid them!",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I used to play piano by ear, but now I use my hands.",
    "Why do ducks have feathers? To cover their butt quacks!",
    "I told my friend ten jokes to make him laugh. Sadly, no pun in ten did.",
    "What did one plate say to another? Dinner’s on me!",
    "What did the grape do when he got stepped on? Nothing, he just let out a little wine!",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one!",
    "What did one ocean say to the other ocean? Nothing, they just waved!",
    "Why don’t eggs tell jokes? They might crack up!",
    "I was wondering why the baseball was getting bigger. Then it hit me!",
    "What do you call a fake noodle? An impasta!",
    "Why did the math book look sad? Because it had too many problems!",
    "How does a penguin build its house? Igloos it together!",
    "Why was the big cat disqualified from the race? Because it was a cheetah!",
    "Why don’t skeletons ever start a band? Because they don’t have the guts!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the coffee file a police report? It got mugged!",
    "What kind of shoes do ninjas wear? Sneakers!",
    "Why was the belt arrested? Because it was holding up a pair of pants!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the banana go to the doctor? Because it wasn’t peeling well!",
    "Why don’t seagulls fly over the bay? Because then they’d be bagels!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What happens to a frog’s car when it breaks down? It gets toad away!",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake!",
    "What do you call cheese that isn’t yours? Nacho cheese!",
    "Why do oranges wear sunscreen? So they don’t peel!",
    "Why can’t your nose be 12 inches long? Because then it would be a foot!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why do cows have hooves instead of feet? Because they lactose!",
    "How do you organize a space party? You planet!",
    "Why did the mushroom go to the party? Because he was a fungi!",
    "Why can’t you give Elsa a balloon? Because she will let it go!",
    "What do you call a sleeping bull? A bulldozer!",
    "Why are ghosts bad at lying? Because they are too transparent!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don’t some fish play piano? Because you can’t tuna fish!",
    "Why was the calendar so popular? Because it had so many dates!",
    "What do you call a bear caught in the rain? A drizzly bear!",
    "Why do bees have sticky hair? Because they use honeycombs!",
    "What kind of tea is hard to swallow? Reality!",
    "Why did the football coach go to the bank? To get his quarterback!",
    "What did one plate say to another plate? Lunch is on me!",
    "Why do skeletons stay so calm? Because nothing gets under their skin!",
    "How do you make a tissue dance? Put a little boogie in it!"
];

module.exports = {
    name: 'joke',
    description: 'Tells a random joke.',
    execute(message) {
        const randomJoke = jokes[Math.floor(Math.random() * jokes.length)];
        message.reply(randomJoke);
    }
};
